// Counter
export const INCREMENT_COUNTER = 'INCREMENT_COUNTER'
export const DECREMENT_COUNTER = 'DECREMENT_COUNTER'

export const FETCH_INSTANCES_REQUEST = 'FETCH_INSTANCES_REQUEST'
export const FETCH_INSTANCES_FAILED = 'FETCH_INSTANCES_FAILED'
export const FETCH_INSTANCES_SUCCESS = 'FETCH_INSTANCES_SUCCESS'

export const FETCH_DEVICES_REQUEST = 'FETCH_DEVICES_REQUEST'
export const FETCH_DEVICES_FAILED = 'FETCH_DEVICES_FAILED'
export const FETCH_DEVICES_SUCCESS = 'FETCH_DEVICES_SUCCESS'

export const FETCH_DEVICE_REQUEST = 'FETCH_DEVICE_REQUEST'
export const FETCH_DEVICE_FAILED = 'FETCH_DEVICE_FAILED'
export const FETCH_DEVICE_SUCCESS = 'FETCH_DEVICE_SUCCESS'
